Cauldron2/Cauldron2/urls.py
from django.contrib import admin
from django.urls import path, include
from CauldronApp import views, oauth
from Cauldron2 import settings

# IMPORTANT: Login paths must be defined in settings.LOGIN_REQUIRED_IGNORE_VIEW_NAMES
urlpatterns = [
    path('oauth/gitlab/<str:backend>', oauth.gitlab.start_oauth, name='gitlab_oauth'),
    path('oauth/github', oauth.github.start_oauth, name='github_oauth'),
    path('oauth/meetup', oauth.meetup.start_oauth, name='meetup_oauth'),
    path('oauth/twitter', oauth.twitter.start_oauth, name='twitter_oauth'),

    path('github-login', views.request_github_oauth, name='github_callback'),
    path('gitlab-login/<str:backend>', views.request_gitlab_oauth, name='gitlab_callback'),
    path('meetup-login', views.request_meetup_oauth, name='meetup_callback'),
    path('twitter-login', views.request_twitter_oauth, name='twitter_callback'),

    path('login', views.request_login, name='login_page'),
    path('logout', views.request_logout, name='logout_page'),
    path('delete-token', views.request_delete_token),
    path('unlink-account', views.request_unlink_account),

    path('compare', views.request_compare_projects, name="compare_projects"),
    path('compare/metrics', views.request_compare_projects_metrics, name="compare_projects_metrics"),

    path('projects', views.request_user_projects, name="user_projects"),
    path('projects/new', views.create_project, name='create_project'),

    path('project/<int:project_id>', views.request_show_project, name="show_project"),
    path('project/<int:project_id>/summary', views.request_project_summary, name="project_summary"),
    path('project/<int:project_id>/rename', views.request_rename_project, name="rename_project"),
    path('project/<int:project_id>/refresh', views.request_refresh_project, name="refresh_project"),
    path('project/<int:project_id>/metrics', views.request_project_metrics, name="project_metrics"),
    path('project/<int:project_id>/workspace', views.request_workspace, name="open_workspace"),
    path('project/<int:project_id>/delete', views.request_delete_project, name="delete_project"),
    path('project/<int:project_id>/public-kibana', views.request_public_kibana, name="open_public_kibana"),
    path('project/<int:project_id>/repositories', views.request_project_repositories, name="show_project_repos"),
    path('project/<int:project_id>/actions', views.request_project_actions, name="show_project_actions"),
    path('project/<int:project_id>/actions/refresh', views.request_project_actions_refresh, name="refresh_project_actions"),
    path('project/<int:project_id>/actions/remove', views.request_project_actions_remove, name="remove_project_actions"),
    path('project/<int:project_id>/repositories/add', views.request_add_to_project, name="add_project_repos"),
    path('project/<int:project_id>/repositories/remove', views.request_remove_from_project, name="remove_project_repos"),
    path('project/<int:project_id>/ongoing-owners', views.request_ongoing_owners, name='project_ongoing_owners'),
    path('project/<int:project_id>/create-git-csv', views.request_create_git_csv, name='project_create_git_csv'),

    path('repository/<int:repo_id>/refresh', views.request_refresh_repository, name='refresh_repository'),
    path('repository/<int:repo_id>/actions', views.request_repo_intentions, name='show_repository_intentions'),
    path('repositories/info', views.request_repos_info),

    path('logs/<int:logs_id>', views.request_logs, name='show_logs'),

    path('admin-kibana', views.request_kibana_admin, name='kibana_admin'),

    path('projects/info', views.request_projects_info),

    path('terms/', views.terms, name="terms"),
    path('privacy/', views.privacy, name="privacy"),
    path('cookies/', views.cookies, name="cookies"),

    path('profile/', include('profile.urls')),

    path('stats/', views.stats_page, name="stats"),

    path('', views.homepage, name="homepage"),
    path('admin/', admin.site.urls),
]

if settings.HATSTALL_ENABLED:
    urlpatterns.insert(0, path('hatstall/', include('hatstall.urls')))

Cauldron2/profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.request_delete_own_user, name="delete_user"),
]

Cauldron2/CauldronApp/models.py
"""
The models are in another application in a new repository.
This decision was made to be able to modify the database from the workers and avoid duplicate code.
Here we import all the 'cauldron' models to make it easier to use from this repository.
"""
from cauldron_apps.cauldron.models import \
    Project, ProjectRole, AnonymousUser, UserWorkspace, \
    Repository, MeetupRepository, GitRepository, GitHubRepository, GitLabRepository, \
    OauthUser

Cauldron2/CauldronApp/views.py
import logging
import datetime
import random
from random import choice
from string import ascii_lowercase, digits
from urllib.parse import urlencode
from dateutil.relativedelta import relativedelta

from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import login, logout, get_user_model
from django.urls import reverse
from django.db import transaction
from django.views.decorators.http import require_http_methods

from Cauldron2 import settings

from CauldronApp import kibana_objects, utils, datasources
from CauldronApp.pages import Pages
from CauldronApp.oauth import GitHubOAuth, GitLabOAuth, MeetupOAuth, TwitterOAuth
from CauldronApp.project_metrics import metrics

from poolsched.models import Intention, ArchivedIntention
from poolsched.models.jobs import Log
from cauldron_apps.poolsched_github.models import GHToken, IGHRaw
from cauldron_apps.poolsched_gitlab.models import GLToken, GLInstance, IGLRaw
from cauldron_apps.poolsched_meetup.models import MeetupToken, IMeetupRaw
from cauldron_apps.poolsched_export.models.iexportgit import IExportGitCSV
from cauldron_apps.cauldron_actions.models import IRefreshActions
from cauldron_apps.cauldron.models import IAddGHOwner, IAddGLOwner, Project, OauthUser, AnonymousUser, \
    UserWorkspace, ProjectRole, Repository, GitLabRepository, GitRepository, GitHubRepository, MeetupRepository, \
    AuthorizedBackendUser

from cauldron_apps.cauldron.opendistro import OpendistroApi

import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

User = get_user_model()


JOB_LOGS = '/job_logs'

ES_IN_URL = "{}://{}:{}".format(settings.ES_IN_PROTO, settings.ES_IN_HOST, settings.ES_IN_PORT)
KIB_IN_URL = "{}://{}:{}{}".format(settings.KIB_IN_PROTO, settings.KIB_IN_HOST, settings.KIB_IN_PORT, settings.KIB_PATH)

logger = logging.getLogger(__name__)


def homepage(request):
    # If user is authenticated, homepage is My projects page
    if request.user.is_authenticated:
        return request_user_projects(request)

    latest_projects = Project.objects.order_by('-created')[:6]

    context = create_context(request)
    context['latest_projects'] = latest_projects

    return render(request, 'cauldronapp/index.html', context=context)


def request_user_projects(request):
    context = create_context(request)
    if not request.user.is_authenticated:
        context['title'] = "You are not logged in"
        context['description'] = "You need to login or create a new project to continue"
        return render(request, 'cauldronapp/error.html', status=400, context=context)
    else:
        projects = Project.objects.filter(creator=request.user)

        search = request.GET.get('search')
        if search is not None:
            projects = projects.filter(name__icontains=search)

        p = Pages(projects, 9)
        page_number = request.GET.get('page', 1)
        page_obj = p.pages.get_page(page_number)
        context['page_obj'] = page_obj
        context['pages_to_show'] = p.pages_to_show(page_obj.number)

        projects_info = list()
        for project in page_obj.object_list:
            summary = project.summary()
            summary['project'] = project
            projects_info.append(summary)
        context['projects_info'] = projects_info
    return render(request, 'cauldronapp/projects/projects.html', context=context)


# TODO: Add state
def request_github_oauth(request):
    """Callback for GitHub authentication"""
    code = request.GET.get('code', None)
    if not code:
        return custom_404(request, "Code not found in the GitHub callback")

    github = GitHubOAuth(settings.GH_CLIENT_ID, settings.GH_CLIENT_SECRET)
    error = github.authenticate(code)
    if error:
        return custom_500(request, error)
    oauth_user = github.user_data()
    is_admin = oauth_user.username in settings.CAULDRON_ADMINS['GITHUB']
    # Save the state of the session
    data_add = request.session.pop('add_repo', None)
    last_page = request.session.pop('last_page', None)
    new_project_info = request.session.get('new_project')
    store_oauth = request.session.get('store_oauth')

    merged, allowed = authenticate_user(request, 'github', oauth_user, is_admin)
    if not allowed:
        return custom_403(request, "You are not allowed to authenticate in this server. "
                                   "Ask any of the administrators for permission.")

    if merged:
        request.session['alert_notification'] = {'title': 'Account merged',
                                                 'message': f"You already had a Cauldron user with this GitHub account."
                                                            f" We have proceeded to merge all the projects and "
                                                            f"visualization in you current account so that you do not "
                                                            f"loose anything"}
    GHToken.objects.update_or_create(user=request.user, defaults={'token': oauth_user.token})

    if data_add and data_add['backend'] == 'github':
        project = Project.objects.filter(id=data_add['proj_id']).first()
        datasources.github.analyze_data(project,
                                        data_add['data'], data_add['commits'],
                                        data_add['issues'], data_add['forks'])

    request.session['new_project'] = new_project_info
    request.session['store_oauth'] = store_oauth

    if last_page:
        return HttpResponseRedirect(last_page)

    return HttpResponseRedirect(reverse('homepage'))


def merge_accounts(user_origin, user_dest):
    """Change the references of that user to another one"""
    OauthUser.objects.filter(user=user_origin).update(user=user_dest)
    Project.objects.filter(creator=user_origin).update(creator=user_dest)
    GHToken.objects.filter(user=user_origin).update(user=user_dest)
    GLToken.objects.filter(user=user_origin).update(user=user_dest)
    MeetupToken.objects.filter(user=user_origin).update(user=user_dest)
    merge_workspaces(user_origin, user_dest)
    merge_admins(user_origin, user_dest)


def merge_admins(old_user, new_user):
    """Convert the new user to admin if the old one was an admin"""
    new_user.is_staff = new_user.is_staff or old_user.is_staff
    new_user.is_superuser = new_user.is_superuser or old_user.is_superuser
    new_user.save()


def merge_workspaces(old_user, new_user):
    """Rewrite all the visualizations from one tenant to the other one"""
    if not hasattr(old_user, 'userworkspace'):
        return
    if not hasattr(new_user, 'userworkspace'):
        create_workspace(new_user)
    obj = kibana_objects.export_all_objects(KIB_IN_URL, settings.ES_ADMIN_PASSWORD, old_user.userworkspace.tenant_name)
    kibana_objects.import_object(KIB_IN_URL, settings.ES_ADMIN_PASSWORD, obj, new_user.userworkspace.tenant_name)


# TODO: Add state
def request_gitlab_oauth(request, backend):
    redirect_uri = request.build_absolute_uri()
    code = request.GET.get('code', None)
    if not code:
        return custom_404(request, "Code not found in the GitLab callback")
    try:
        instance = GLInstance.objects.get(slug=backend)
    except GLInstance.DoesNotExist:
        return custom_404(request, f"Backend '{backend}' does not exist in this server")
    gitlab = GitLabOAuth(instance, redirect_uri)
    error = gitlab.authenticate(code)
    if error:
        return custom_500(request, error)
    oauth_user = gitlab.user_data()
    is_admin = oauth_user.username in settings.CAULDRON_ADMINS.get(backend.upper(), [])

    # Save the state of the session
    data_add = request.session.pop('add_repo', None)
    last_page = request.session.pop('last_page', None)
    new_project_info = request.session.get('new_project')
    store_oauth = request.session.get('store_oauth')

    merged, allowed = authenticate_user(request, backend, oauth_user, is_admin)
    if not allowed:
        return custom_403(request, "You are not allowed to authenticate in this server. "
                                   "Ask any of the administrators for permission.")

    if merged:
        request.session['alert_notification'] = {'title': 'Account merged',
                                                 'message': f"You already had a Cauldron user with this GitLab account."
                                                            f" We have proceeded to merge all the projects and "
                                                            f"visualization in you current account so that you do not "
                                                            f"loose anything"}

    GLToken.objects.update_or_create(user=request.user, instance=instance, defaults={'token': oauth_user.token})

    if data_add and data_add['backend'] == backend:
        project = Project.objects.get(id=data_add['proj_id'])
        datasources.gitlab.analyze_data(project,
                                        data_add['data'], data_add['commits'],
                                        data_add['issues'], data_add['forks'],
                                        instance=instance)

    request.session['new_project'] = new_project_info
    request.session['store_oauth'] = store_oauth

    if last_page:
        return HttpResponseRedirect(last_page)

    return HttpResponseRedirect(reverse('homepage'))


# TODO: Add state
def request_meetup_oauth(request):
    error = request.GET.get('error', None)
    if error:
        return custom_404(request, f"Meetup callback error. {error}")
    code = request.GET.get('code', None)
    if not code:
        return custom_404(request, "Code not found in the Meetup callback")
    redirect_uri = request.build_absolute_uri(reverse('meetup_callback'))
    meetup = MeetupOAuth(settings.MEETUP_CLIENT_ID, settings.MEETUP_CLIENT_SECRET, redirect_uri)
    error = meetup.authenticate(code)
    if error:
        return custom_500(request, error)

Cauldron2/CauldronApp/templates/cauldronapp/base.html
{% load static %}
{% load admin_urls %}

{% url 'homepage' as homepage %}
{% url 'compare_projects' as compare_projects %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Software development analytics online tool by Bitergia">

  <!--Required Social Media Tags -->
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Level up Software Development Analytics - Cauldron">
  <meta name="twitter:description" content="Cauldron allows project managers, analysts, and developers to understand more about the community and processes involved in software development"/>
  <meta name="twitter:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'img/cauldron_logo.jpg' %}"/>
  <meta property="og:title" content="Level up Software Development Analytics - Cauldron" />
  <meta property="og:description" content="Cauldron allows project managers, analysts, and developers to understand more about the community and processes involved in software development" />
  <meta property="og:image" content= "{{ request.scheme }}://{{ request.get_host }}{% static 'img/cauldron_logo.jpg' %}"/>


  <!-- Cookie consent -->
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
  <script>
  window.addEventListener("load", function(){
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#edeff5",
        "text": "#838391"
      },
      "button": {
        "background": "#4b81e8"
      }
    },
    "showLink": false,
    "position": "bottom-right",
    "content": {
      "message": "This website uses cookies to remember your preferences, and to learn about how people are using the system."
    }
  })});
  </script>

  {% if google_analytics_id %}
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id={{ google_analytics_id }}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '{{google_analytics_id}}');
  </script>
  {% endif %}

  {% if plausible_analytics_enabled %}
  <!-- Plausible Analytics JS -->
  <script async defer data-domain={{request.get_host}} src="https://plausible.io/js/plausible.js"></script>
  {% endif %}

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- SB Admin 2 styles -->
  <link rel="stylesheet" href="{% static 'css/sb-admin-2.min.css' %}">

  <!-- Bootstrap Select CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.18/dist/css/bootstrap-select.min.css">

  <!-- Awesome icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/common.css' %}">

  <!-- Favicon.ico -->
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>

  {% block css%}
  {% endblock %}

  <title>Cauldron - Level Up Software Development Analytics</title>
</head>

<body>
  <!-- BEGIN NAVBAR -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand mr-auto" href="{% url 'homepage' %}">
        <img src="{% static '/img/cauldron-logo-white.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Cauldron <sup class="badge badge-secondary">carazo</sup>
      </a>

      {% if request.resolver_match.url_name != 'show_project' and request.resolver_match.url_name != 'create_project' and request.resolver_match.url_name != 'login_page' or repositories_count > 0 %}
      <a class="btn btn-icon-split btn-orange mx-2" href="{% url 'create_project' %}">
        <span class="icon"><i class="fas fa-plus"></i></span>
        <span class="text">New project</span>
      </a>
      {% endif %}


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarOptions" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarOptions">
        <ul class="navbar-nav mr-auto">

          {% if authenticated and request.path != homepage %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage' %}">My Projects</a>
          </li>
          {% endif %}
          {% if request.user.is_superuser and hatstall_url %}
          <li class="nav-item">
            <a class="nav-link" target="_blank" href="{{ hatstall_url }}">Hatstall</a>
          </li>
          {% endif %}
          {% if authenticated and request.path != compare_projects %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'compare_projects' %}">Compare</a>
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle navbar-text" href="#" id="dropdownCommunityMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Community
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownCommunityMenu">
              <a class="dropdown-item" href="https://community.cauldron.io/" target="_blank">Get Support</a>
              <a class="dropdown-item" href="https://gitlab.com/cauldronio/cauldron/issues/new" target="_blank">Report an Issue</a>
				      <a class="dropdown-item" href="https://mailchi.mp/003f1e1f6242/cauldron-newsletter" target="_blank">Join the Newsletter</a>
              <a class="dropdown-item" href="{% url 'stats' %}" target="_blank">Cauldron Stats</a>
            </div>
          </li>
        </ul>

        <div class="navbar-line d-none"></div>

        {% if authenticated %}
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle navbar-text p-0" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span> {{ request.user.first_name }} </span>
            <img src="{{ photo_user }}" class="rounded-circle avatar">
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'homepage' %}">My projects</a>
            <a class="dropdown-item" href="{% url 'profile:index' %}">Settings</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/logout">Log out</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Administration</h6>
            {% if request.user.is_superuser %}
            <a class="dropdown-item" target="_blank" href="{% url 'kibana_admin' %}">Kibana admin</a>
            <a class="dropdown-item" href="{% url 'admin:index' %}">Django admin</a>
            {% if plausible_analytics_url %}
            <a class="dropdown-item" target="_blank" href="{{ plausible_analytics_url }}">Plausible Analytics</a>
            {% endif %}
            {% if matomo_enabled %}
            <a class="dropdown-item" target="_blank" href="{{ matomo_url }}">Matomo</a>
            {% endif %}
            {% endif %}


            <!--<a class="dropdown-item" href="/profile">Profile</a>-->
          </div>
        </div>
        {% elif request.resolver_match.url_name != 'login_page' %}
        <a class="btn btn-light d-block d-lg-inline-block mb-0 ml-md-3" href="#" data-toggle="modal" data-target="#modalLogin">
          Login
        </a>
        {% endif %}
      </div>

    </div>
  </nav>
  <!-- END NAVBAR-->


  <!-- BEGIN Modal for login -->
  {% if request.resolver_match.url_name != 'login_page' %}
  <div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="modalLoginTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      {% include "cauldronapp/utils/modal_login.html" %}
    </div>
  </div>

  {% endif %}
  <!-- END Modal for login -->


  <!-- BEGIN Container for alerts -->
  <div class="container">
    <div id="alert-container" style="display: none;">
    </div>
  </div>
  <!-- END Container for alerts-->

  <!-- BEGIN Toast list for notifications-->
  <div aria-live="polite" aria-atomic="true" style="position: fixed; width: 100%; bottom: 50px; z-index: 9999;">
    <!-- Position it -->
    <div id="toast-container">

    </div>
  </div>
  <!-- END Toast list for notifications-->


  <div>
    {% block sidebar %}
    {% endblock %}
    <div class="site-content {% if sidebar %}content-moved{% endif %}">
      {% block content %}
      {% endblock %}
      <footer class="footer-position bg-dark text-white pt-3">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-3 offset-md-1">
                <div><a href="https://bitergia.com" target="_blank"><img src="/static/img/bitergia-w-logo-s.png" alt="Bitergia" width="120"></a></div>
                  <p style="display:inline-block">Copyright &copy; 2021 <a href="https://bitergia.com">Bitergium SLL.</a> and its
                    contributors.</p>
                  <p>Some Rights Reserved.</p>
                  <p>
                    <a href="{% url 'terms' %}" target="_blank">Terms</a> |
                    <a href="{% url 'privacy' %}" target="_blank">Privacy</a> |
                    <a href="{% url 'cookies' %}" target="_blank">Cookies Policy</a>
                </p>
              </div>
              <div class="col-md-4">
                <p><a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">
                  <img src="/static/img/by-sa.png" width="120" alt="Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)">
                </a></p>
                <p>Cauldron and the Cauldron logo are
                  trademarks of <a href="https://bitergia.com" target="_blank">Bitergium SLL.</a> in the European Union and/or
                  other jurisdictions. All other trademarks are the property of their respective holders.</p>
              </div>
              <div class="col-md-4">
              <p>Made with <abbr title="love"><span style="color: red; font-size: 1.2rem;">&hearts;</span></abbr> and <strong><a href="https://cauldronio.gitlab.io" target="_blank">free, open source software</a></strong> based on:</p>
              <p>
                <a href="https://chaoss.github.io/grimoirelab/" target="_blank"><img src="/static/img/wizard-y.svg"
                    height="24" alt=""> GrimoireLab</a> |
                <a href="https://www.djangoproject.com/" target="_blank">Django</a> |
                <a href="https://opendistro.github.io/for-elasticsearch/" target="_blank">Open Distro for Elasticsearch</a>
              </p>
              <p>
                <a href="https://status.cauldron.io/">Status</a> |
                Follow us on <a href="https://twitter.com/cauldronio" target="_blank"><i class="fab fa-twitter" style="background: none;"></i> @cauldronio</a> |
                <a href="https://mailchi.mp/003f1e1f6242/cauldron-newsletter" target="_blank"><i class="fa fa-envelop"></i> Newsletter</a>
              </p>

            </div>
            </div>
          </div>

      </footer>
    </div>
  </div>

  <!-- BEGIN Container for modals -->
  <div class="modal" tabindex="-1" role="dialog" id="modal-alert">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p></p>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- END Container for modals-->

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <!-- Bootstrap Select JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.18/dist/js/bootstrap-select.min.js"></script>

  <script src="{% static 'js/common.js' %}" charset="utf-8"></script>

  {% block javascript %}
  {% endblock %}
  {% if alert_notification %}
  <script>
    showModalAlert("{{ alert_notification.title }}", "{{alert_notification.message}}", '<button type="button" class="btn btn-info" data-dismiss="modal">OK</button>')
  </script>
  {% endif %}

</body>

</html>

Cauldron2/CauldronApp/templates/cauldronapp/error.html
{% extends "cauldronapp/base.html" %}
{% load static %}

{% block css%}
{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-md-center h-45">
    <div class="col-md-8 error-box shadow border p-5 mb-5 bg-white rounded text-center ">
      <h1 class="text-danger">{{title}}</h1>
      <h3 class="p-3">{{description}}</h3>
    </div>
  </div>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

Cauldron2/CauldronApp/templates/cauldronapp/login.html
{% extends "cauldronapp/base.html" %}


{% block content %}
<div class="row justify-content-center">
  <div class="m-3 col-xs-auto">
    {% include "cauldronapp/utils/modal_login.html" %}
  </div>
</div>
{% endblock %}

Cauldron2/CauldronApp/templates/cauldronapp/stats.html
{% extends "cauldronapp/base.html" %}
{% load static %}

{% block css%}
{% endblock %}

{% block content %}
<div class="container">
    <div class="h3 mt-5 mb-5 font-weight-bold text-dark text-uppercase">General stats</div>

    {% include "cauldronapp/utils/status_card.html" %}
</div>
{% endblock %}

{% block javascript %}
{% endblock %}